### ISSUE TITLE
zod-mock: getting generator is not a function when upgrading from 3.5.6 to 3.5.7

### ISSUE THREAD

**Issue by stefanmo** [anatine/zod-plugins#57]
Initially I had installed 3.5.6 and upgraded all dependencies in my project and started receiving this error when running the tests:
```
TypeError: generator is not a function
        at Object.parseString [as ZodString] (/.../node_modules/.pnpm/@anatine+zod-mock@3.5.9_g6sp5rb3j7f67qdwsibxgel264/packages/zod-mock/src/lib/zod-mock.ts:233:13)
        at generateMock (/.../node_modules/.pnpm/@anatine+zod-mock@3.5.9_g6sp5rb3j7f67qdwsibxgel264/packages/zod-mock/src/lib/zod-mock.ts:432:33)
        at /.../node_modules/.pnpm/@anatine+zod-mock@3.5.9_g6sp5rb3j7f67qdwsibxgel264/packages/zod-mock/src/lib/zod-mock.ts:20:14
```
Started playing with dependencies and narrowed it down to zod-mock
If I keep all dependencies upgraded and downgrade only zod-mock then the issue goes away. If I upgrade from 3.5.6 to 3.5.7 it then throws errors.

**Comment by stefanmo** [comment]
@Brian-McBride does zod-mock now use faker 7? Because if I upgrade to 7 then this error goes away. However, doing so leads to unmet peer dependencies since the library says that it should use faker 6.

**Comment by Brian-McBride** [comment]
I fixed the updates. 
Github actions are not running today for some reason. 
When they do, there will be a release to address this.
